---
- hosts: lab
  user: centos
  become: yes
  vars:

  roles:
    - { role: general, tags: general}
#    - { role: tier1, tags: tier1}
#    - { role: tier2, tags: tier2}
#    - { role: exam, tags: exam}
#    - { role: general_install, tags: general_install}
#    - { role: etais, tags: etais }
#    - { role: dns, tags: dns }
#    - { role: apache, tags: apache}
#    - { role: email, tags: email}
#    - { role: tls, tags: tls}
#    - { role: fs, tags: fs}
#    - { role: docker, tags: docker}
#    - { role: devops, tags: devops}
#    - { role: kubernetes, tags: kubernetes}
#    - { role: monitoring, tags: monitoring}
    - { role: final, tags: final}
