---
- hosts: lab
  user: centos
  become: yes
  vars:

  roles:
    - { role: general, tags: general}
    - { role: general_install, tags: general_install}
    - { role: etais, tags: etais }
    - { role: dns, tags: dns }
    - { role: apache, tags: apache}
    - { role: email, tags: email}
    - { role: tls, tags: tls}
    - { role: fs, tags: fs}
    - { role: docker, tags: docker} # Needs to be before devops because we copy daemon.json
    - { role: devops, tags: devops}
#    - { role: kubernetes, tags: kubernetes}
#    - { role: monitoring, tags: monitoring}
    - { role: final, tags: final}
