---
- hosts: all
  user: centos
  become: yes
  vars:

  roles:
#    - { role: etais, tags: etais }
#    - { role: dns, tags: dns }
#    - { role: apache, tags: apache}
    - { role: email, tags: email}
