- name: Get OpenStack metadata
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    method: GET
    status_code: 200
    return_content: yes
  register: cloud_metadata
- set_fact:
    external_ip: "{{ cloud_metadata.content }}"
    quad_1: "{{ cloud_metadata.content.split('.')[0] }}"
    quad_2: "{{ cloud_metadata.content.split('.')[1] }}"
    quad_3: "{{ cloud_metadata.content.split('.')[2] }}"
    quad_4: "{{ cloud_metadata.content.split('.')[3] }}"

- name: Include vars.yml
  ansible.builtin.include_vars:
    file: "group_vars/vars.yml"

- name: Print external ip
  ansible.builtin.debug:
    msg: External IP is {{ external_ip }}


